### ISSUE TITLE
Please update github release to 0.1.1 (so module can be used with Foundry 11)

### ISSUE THREAD

**Issue by BearBackyardRuler** [EndlesNights/FoundryPathfinding#3]
<img width="195" alt="image" src="https://github.com/EndlesNights/FoundryTacticalPathfinding/assets/138624050/cc6efacd-94ba-4043-9c2e-9b9650ad409c">

The official release for this project shows as 0.1.0 (see screenshot).

When using the manifest link, the 0.1.0 version is downloaded instead of the newer 0.1.1 version.

Please allow the 0.1.1 version to be downloaded.

Thanks.

**Comment by EndlesNights** [comment]
Sorry this took so long, manifest link fixed.
